### ISSUE TITLE
[4.17.16] require('lodash').runInContext(); is not a function

### ISSUE THREAD

**Issue by impacmp** [lodash/lodash#4845]
something went wrong with your v4.17.16 update. For example usage of grunt will crash because of lodash usage in grunt-legacy-util:

..../node_modules/grunt-legacy-util/index.js:26
var _ = util._ = require('lodash').runInContext();
                                   ^

[TypeError: require(...).runInContext is not a function
  at Object.<anonymous> (/.../node_modules/grunt-legacy-util/index.js:26:36)
....

Force the usage of lodash v4.17.15 solves the problem, so it seems to be a problem with v4.17.16

Would you please fix this as soon as possible, since it breaks multiple build pipelines

**Comment by kebichishaobing** [comment]
We have the same situationuninstall lodash, and install lodash@4.17.15

**Comment by anthony-telljohann** [comment]
We're also seeing the exact same error with our use of `grunt-legacy-util`

**Comment by impacmp** [comment]
seems to work with v4.17.17, I just had to delete the package-lock.json and run "npm install"

**Comment by mathiasbynens** [comment]
Please give `lodash@4.17.18` a try. Details here: https://github.com/lodash/lodash/issues/4837#issuecomment-655609600
