### ISSUE TITLE
.value() breaking change in lodash 4.0.1

### ISSUE THREAD

**Issue by tteltrab** [lodash/lodash#1879]
Getting the error:
>TypeError: _(...).map(...).flatten(...).uniq(...).filter(...).each(...).value is not a function

This worked in 4.0.0, stopped working in 4.0.1.
Here's what the code in question looks like (more or less):
```
_(array)
    .map(function (object) {
        ...
    })
    .flatten()
    .uniq()
    .filter(function (object) {
        ...
    })
    .each(function (feature, index, list) {
        ...
    })
    .value();
```

**Comment by jdalton** [comment]
Yep, read the [changelog](https://github.com/lodash/lodash/wiki/Changelog#v400). It's in there.

**Comment by tteltrab** [comment]
perfect, thanks.  threw me off that it wasn't breaking in 4.0.0 but is in 4.0.1, so didn't read that changelog from January 12th as closely as I should have apparently.

**Comment by jdalton** [comment]
That's because v4.0 had a bug that caused it's alias `each` to have the incorrect behavior while `forEach` worked as documented in the changelog.
